# Generated by Django 4.2.10 on 2024-03-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_message_receiver_chatroom_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='name',
            field=models.BinaryField(),
        ),
    ]
