# Generated by Django 4.2.10 on 2024-03-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_alter_chatroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='encryption_key',
            field=models.BinaryField(default=None),
        ),
    ]
