# Generated by Django 4.2.10 on 2024-03-11 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_chatroom_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='encryption_key',
            field=models.BinaryField(),
        ),
    ]
