# Generated by Django 4.2.10 on 2024-03-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_chatroom_encryption_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='encrypted_content',
            field=models.CharField(max_length=255),
        ),
    ]
