# Generated by Django 4.2.10 on 2024-03-02 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_role_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrole',
            name='role',
        ),
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ManyToManyField(to='models.role'),
        ),
    ]
